### ISSUE TITLE
Feature request: specify cognito client id

### ISSUE THREAD

**Issue by revmischa** [aiji42/next-fortress#133]
Right now next-fortress uses a regex to get the token `/CognitoIdentityServiceProvider\..+\.idToken/.test(key)`

Because I have multiple cognito clients I test with (dev, prod) it would be nice if I could pass in the web client ID to use there so we don't have to wildcard finding the token in cookies.

Thanks for the cool library!

**Comment by aiji42** [comment]
@revmischa Thanks for your valuable idea.

I would like to be able to specify the client id as you suggested.

**Comment by aiji42** [comment]
I have decided that it would be better to make it required rather than optional. Due to the destructive change in the type of the `makeCognitoInspector` argument, I' ll make the next release a major version.
#138

**Comment by revmischa** [comment]
Amazing, thanks for this!
