### ISSUE TITLE
middleware内で相対パスを使用するとエラーが起きます。

### ISSUE THREAD

**Issue by rnrnstar2** [aiji42/next-fortress#176]
いつもtwitterを拝見して参考にさせていただいております。
この度ミドルウェアでの認証を実装するにあたり、こちらのライブラリを使用させていただきました。
簡単に実装ができるので、とても助かっております。

今回next.jsのバージョンが上がり、相対パスがNGになりましたので、「destination: '/signin'」部分でエラーになります。
そのため内部で絶対パスに変更されるように改良していただけると嬉しいです。
https://nextjs.org/docs/messages/middleware-relative-urls

よろしくお願いいたします。

**Comment by aiji42** [comment]
I have fixed this bug and released a new version (v4.0.1).
