### ISSUE TITLE
Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by revmischa** [aiji42/next-fortress#189]
Started getting this all of a sudden when running locally. Goes away if I clear cookies.

<img width="1098" alt="Screen Shot 2022-05-26 at 22 45 17" src="https://user-images.githubusercontent.com/245131/170637804-4e1ac555-fe88-40c7-927a-c9c2a28113a8.png">

**Comment by aiji42** [comment]
Sorry for the late response.
From the error capture, I assumed you were using cognito. Did you set the `region`, `userPoolId ` and `userPoolWebClientId` correctly as per the documentation? From the number of lines that are generating errors, it appears that they are either not set or are set incorrectly.

**Comment by revmischa** [comment]
yes they're set
```ts
import { region, userPoolId, userPoolWebClientId } from "@frontend/config/next"
import { makeCognitoInspector } from "next-fortress"
import { NextMiddleware, NextResponse } from "next/server"

if (!userPoolId || !userPoolWebClientId) throw new Error("userPoolId or userPoolWebClientId is missing in config")
const redirecter: NextMiddleware = (req) =>
  NextResponse.redirect("/login?next=" + req.nextUrl.pathname + req.nextUrl.search)

// require a logged-in user
export const middleware = makeCognitoInspector(redirecter, { region, userPoolId, userPoolWebClientId })
```

**Comment by aiji42** [comment]
Can you access this URL to get the public key?
`https://cognito-idp.${region}.amazonaws.com/${userPoolId}/.well-known/jwks.json`

**Comment by aiji42** [comment]
The next-fortress cognito plugin fetches the above URL and verifies the token by obtaining the public key.
The error screenshot you shared shows that it fails to get that key.

**Comment by revmischa** [comment]
I think the problem went away for now, thanks for the response, will re-open if I run into this again
